package model;

import java.time.LocalDate;
import java.util.List;
import java.time.format.DateTimeFormatter;


public class Invoice {

    /* ================= IDENTITY ================= */

    private int invoiceNo;                 // Generated by DAO
    private LocalDate invoiceDate = LocalDate.now();

    /* ================= BUYER ================= */

    private String buyerName;
    private String buyerAddress;
    private String buyerGst;
    private String buyerState;
    private String buyerStateCode;

    /* ================= CONSIGNEE ================= */

    private String consigneeName;
    private String consigneeAddress;
    private String consigneeGst;
    private String consigneeState;
    private String consigneeStateCode;

    /* ================= REFERENCES ================= */

    private String termsOfPayment;
    private String poNo;
    private LocalDate poDate;
    private String dcNo;
    private LocalDate dcDate;
    private String dispatchThrough;
    private String ewayBillNo;

    /* ================= TOTALS (FINAL) ================= */

    private double taxableAmount;
    private double cgstTotal;
    private double sgstTotal;
    private double igstTotal;
    private double roundOff;
    private double grandTotal;

    /* ================= ITEMS (OPTIONAL CARRIER) ================= */

    // Not persisted directly; DAO controls storage
    private List<InvoiceItem> items;

    /* =====================================================
       CANONICAL GETTERS USED BY DAO (DO NOT RENAME)
       ===================================================== */

    public double getTaxableAmount() {
        return taxableAmount;
    }

    public double getCgstTotal() {
        return cgstTotal;
    }

    public double getSgstTotal() {
        return sgstTotal;
    }

    public double getIgstTotal() {
        return igstTotal;
    }

    public double getRoundOff() {
        return roundOff;
    }

    public double getGrandTotal() {
        return grandTotal;
    }

    /* ================= STANDARD GETTERS / SETTERS ================= */

    public int getInvoiceNo() {
        return invoiceNo;
    }

    public void setInvoiceNo(int invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    public LocalDate getInvoiceDate() {
        return invoiceDate;
    }

    public void setInvoiceDate(LocalDate invoiceDate) {

        if (this.invoiceDate != null && this.invoiceNo != 0) {
            throw new IllegalStateException(
                    "Invoice date cannot be modified after invoice is saved"
            );
        }

        this.invoiceDate = (invoiceDate != null)
                ? invoiceDate
                : LocalDate.now();
    }

    // ===== DAO ONLY – DO NOT USE IN UI / LOGIC =====
    public void _setInvoiceDateFromDB(LocalDate invoiceDate) {
        this.invoiceDate = invoiceDate;
    }


    // -------- Buyer --------

    public String getBuyerName() {
        return buyerName;
    }

    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    public String getBuyerAddress() {
        return buyerAddress;
    }

    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    public String getBuyerGst() {
        return buyerGst;
    }

    public void setBuyerGst(String buyerGst) {
        this.buyerGst = buyerGst;
    }

    public String getBuyerState() {
        return buyerState;
    }

    public void setBuyerState(String buyerState) {
        this.buyerState = buyerState;
    }

    public String getBuyerStateCode() {
        return buyerStateCode;
    }

    public void setBuyerStateCode(String buyerStateCode) {
        this.buyerStateCode = buyerStateCode;
    }

    // -------- Consignee --------

    public String getConsigneeName() {
        return consigneeName;
    }

    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName;
    }

    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress;
    }

    public String getConsigneeGst() {
        return consigneeGst;
    }

    public void setConsigneeGst(String consigneeGst) {
        this.consigneeGst = consigneeGst;
    }

    public String getConsigneeState() {
        return consigneeState;
    }

    public void setConsigneeState(String consigneeState) {
        this.consigneeState = consigneeState;
    }

    public String getConsigneeStateCode() {
        return consigneeStateCode;
    }

    public void setConsigneeStateCode(String consigneeStateCode) {
        this.consigneeStateCode = consigneeStateCode;
    }

    // -------- References --------

    public String getTermsOfPayment() {
        return (termsOfPayment == null || termsOfPayment.isBlank())
                ? "CREDIT"
                : termsOfPayment;
    }


    public void setTermsOfPayment(String termsOfPayment) {
        this.termsOfPayment = termsOfPayment;
    }

    public String getPoNo() {
        return poNo;
    }

    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    public LocalDate getPoDate() {
        return poDate;
    }

    public void setPoDate(LocalDate poDate) {
        this.poDate = poDate;
    }

    public String getDcNo() {
        return dcNo;
    }

    public void setDcNo(String dcNo) {
        this.dcNo = dcNo;
    }

    public LocalDate getDcDate() {
        return dcDate;
    }

    public void setDcDate(LocalDate dcDate) {
        this.dcDate = dcDate;
    }

    public String getDispatchThrough() {
        return dispatchThrough;
    }

    public void setDispatchThrough(String dispatchThrough) {
        this.dispatchThrough = dispatchThrough;
    }

    public String getEwayBillNo() {
        return ewayBillNo;
    }

    public void setEwayBillNo(String ewayBillNo) {
        this.ewayBillNo = ewayBillNo;
    }

    // -------- Totals setters --------

    public void setTaxableAmount(double taxableAmount) {
        this.taxableAmount = taxableAmount;
    }

    public void setCgstTotal(double cgstTotal) {
        this.cgstTotal = cgstTotal;
    }

    public void setSgstTotal(double sgstTotal) {
        this.sgstTotal = sgstTotal;
    }

    public void setIgstTotal(double igstTotal) {
        this.igstTotal = igstTotal;
    }

    public void setRoundOff(double roundOff) {
        this.roundOff = roundOff;
    }

    public void setGrandTotal(double grandTotal) {
        this.grandTotal = grandTotal;
    }

    // -------- Items (optional) --------

    public List<InvoiceItem> getItems() {
        return items;
    }

    public void setItems(List<InvoiceItem> items) {
        this.items = items;
    }

    // ===== Display helpers (DO NOT use for DB) =====
    private static final DateTimeFormatter DISPLAY_DATE =
            DateTimeFormatter.ofPattern("dd-MM-yyyy");

    public String getInvoiceDateFormatted() {
        return invoiceDate != null
                ? DISPLAY_DATE.format(invoiceDate)
                : "";
    }

}
